export const ZendeskApiUrls = {
  SingleArticle: 'api/v2/help_center/en-us/articles/',
}

export const GlossaryIds = {
  ACTIVE_CANDIDACY: 4,
  WITHDRAWN_CANDIDACY: 2,
  ACTIVATE_CANDIDACY: 3,
}

export const GlossaryCategoriesOptions = [
  {
    value: 'All',
    label: 'All Categories',
  },
]

// Tooltip locations enum mapped to the Glossary Id
export const TooltipLocations = {
  PROFILE_MINING_WALLET: 3,
  PROFILE_MISSIONS_WALLET: 9,
  MISSIONS_BSC_NETWORK: 9,
  MISSIONS_START_MISSION: 10,
  MISSIONS_INFO_TLM_LOCKED: 43,
  MINING_INVENTORY: 22,
  MINING_LAND_STATS_TITLE: 39,
  MINING_LAND_STATS_CHARGE_TIME: 23,
  MINING_LAND_STATS_MINING_POWER: 27,
  MINING_LAND_STATS_NFT_POWER: 36,
  MINING_LAND_STATS_SHARDS: 37,
  MINING_LAND_STATS_POW: 24,
  INVENTORY_TABS: 16,
  SHINING_TITLE: 26,
  GOVERNANCE_PLANET_DETAILS: 18,
  GOVERNANCE_HEADER: 44,
  GOVERNANCE_HEADER_PLANET_TREASURY: 60,
  GOVERNANCE_HEADER_CUSTODIAN_BUDGET: 61,
  GOVERNANCE_MEMBER_TERMS: 46,
  GOVERNANCE_PLANET_DETAILS_SNAP_ELECTION: 55,
  GOVERNANCE_PLANET_DETAILS_CUSTODIANS: 54,
  GOVERNANCE_PLANET_DETAILS_PROPOSAL: 66,
  GOVERNANCE_CANDIDATE_VOTING: 52,
  GOVERNANCE_CANDIDATE_VOTING_POWER: 56,
  GOVERNANCE_CANDIDATE_VOTE_DECAY: 57,
  GOVERNANCE_BECOME_CANDIDATE: 64,
  GOVERNANCE_SIDEBAR_AVAILABLE_TOKENS: 47,
  GOVERNANCE_SIDEBAR_STAKED_TOKENS: 48,
  GOVERNANCE_SIDEBAR_TOKEN_RELEASE_DATE: 49,
}
